// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWeZpzeRR6y1wAjPkXDuXW0IVXj2xI4ic',
    appId: '1:375579772921:web:bc2a9641c353206ce51f28',
    messagingSenderId: '375579772921',
    projectId: 'sudani-5e662',
    authDomain: 'sudani-5e662.firebaseapp.com',
    storageBucket: 'sudani-5e662.firebasestorage.app',
    measurementId: 'G-CD2E71Q0JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjC3S2ZTJU04EOo98wBp5b1MaEhmr2bo',
    appId: '1:375579772921:android:8d77ebada0d09827e51f28',
    messagingSenderId: '375579772921',
    projectId: 'sudani-5e662',
    storageBucket: 'sudani-5e662.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn4rXNnb-ZbXQU_WS6Jh6S_WO1eUbJCcU',
    appId: '1:375579772921:ios:3b5c0bc94525ed3be51f28',
    messagingSenderId: '375579772921',
    projectId: 'sudani-5e662',
    storageBucket: 'sudani-5e662.firebasestorage.app',
    iosClientId: '375579772921-s4srvasu4kgrju7bgqnm62aev1stt13n.apps.googleusercontent.com',
    iosBundleId: 'com.example.sudaniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn4rXNnb-ZbXQU_WS6Jh6S_WO1eUbJCcU',
    appId: '1:375579772921:ios:3b5c0bc94525ed3be51f28',
    messagingSenderId: '375579772921',
    projectId: 'sudani-5e662',
    storageBucket: 'sudani-5e662.firebasestorage.app',
    iosClientId: '375579772921-s4srvasu4kgrju7bgqnm62aev1stt13n.apps.googleusercontent.com',
    iosBundleId: 'com.example.sudaniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWeZpzeRR6y1wAjPkXDuXW0IVXj2xI4ic',
    appId: '1:375579772921:web:097155a3286b911de51f28',
    messagingSenderId: '375579772921',
    projectId: 'sudani-5e662',
    authDomain: 'sudani-5e662.firebaseapp.com',
    storageBucket: 'sudani-5e662.firebasestorage.app',
    measurementId: 'G-TD1KZMZ8YF',
  );
}


